# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11cc77145daa0583c6e036e247eef1df748f689ec65795b6cfba5a212560626e6254ed4236da61225fb0c4f6344c197a9012d720a24f72cd27d59e8dd8451aca

test:
  secret_key_base: 3604d3e1d3f7f3ab61430462542cd994ab57b8da49013be93413872c41c28a0afa2d8e7138b298074121e7d145b006c955be1574d6e1303386deb8a03a90900e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
